This file has been removed as it is no longer needed.
paths:
  /service-areas:
    post:
      summary: Create a new service area
      tags:
        - ServiceArea
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - service
              properties:
                service:
                  type: string
                  description: Service ObjectId
                  example: 60f7c0b8e1b1c8a1b8e1b1c9
                availableLocations:
                  type: array
                  items:
                    type: string
                    description: ObjectId referencing Service.locationAvailable (subdocument)
                  description: Array of ObjectIds referencing Service.locationAvailable
                  example:
                    ['650000000000000000000001', '650000000000000000000002']
                aadhaarFrontImage:
                  type: string
                  format: binary
                  description: aadhaar front image file
                aadhaarBackImage:
                  type: string
                  format: binary
                  description: aadhaar back image file
                panImage:
                  type: string
                  format: binary
                  description: PAN image file
      responses:
        '201':
          description: Service area created successfully
          content:
            application/json:
              schema:
                $ref: '../schemas/serviceArea.yaml#/ServiceArea'
        '400':
          description: Invalid input
        '500':
          description: Server error
    get:
      summary: Get all service areas (admin only)
      tags:
        - ServiceArea
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, approved, rejected, suspended]
          description: Filter by application status
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Results per page
      responses:
        '200':
          description: Service areas fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/serviceArea.yaml#/ServiceArea'
        '400':
          description: Invalid filter
        '500':
          description: Server error
  /service-areas/{id}:
    get:
      summary: Get a single service area by ID
      tags:
        - ServiceArea
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Service area ObjectId
      responses:
        '200':
          description: Service area fetched successfully
          content:
            application/json:
              schema:
                $ref: '../schemas/serviceArea.yaml#/ServiceArea'
        '404':
          description: Service area not found
        '400':
          description: Invalid ID
        '500':
          description: Server error
  /service-areas/{id}/status:
    patch:
      summary: Update service area status (admin only)
      tags:
        - ServiceArea
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Service area ObjectId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - applicationStatus
              properties:
                applicationStatus:
                  type: string
                  enum: [pending, approved, rejected, suspended]
                  description: New status
                  example: approved
                adminNotes:
                  type: string
                  description: Optional admin notes
      responses:
        '200':
          description: Service area status updated successfully
          content:
            application/json:
              schema:
                $ref: '../schemas/serviceArea.yaml#/ServiceArea'
        '404':
          description: Service area not found
        '400':
          description: Invalid status or ID
        '500':
          description: Server error
