openapi: 3.0.3
info:
  title: Service API
  version: 1.0.0
  description: API for service management and retrieval
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Local development server
tags:
  - name: Auth
    description: Authentication management
  - name: Categories
    description: Category management
  - name: Service
    description: Service management and retrieval
paths:
  /services:
    post:
      summary: Create a new service
      tags:
        - Service
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
                - description
                - category
                - price
                - duration
              properties:
                title:
                  type: string
                  description: Service title
                  example: Home Cleaning
                description:
                  type: string
                  description: Service description
                  example: Professional home cleaning service
                category:
                  type: string
                  description: Category ObjectId
                  example: 60f7c0b8e1b1c8a1b8e1b1c8
                price:
                  type: number
                  description: Service price
                  example: 1000
                duration:
                  type: number
                  description: Duration in minutes
                  example: 60
                icon:
                  type: string
                  format: binary
                  description: Icon image file (optional)
                media:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Up to 5 media files (optional)
                locationAvailable:
                  type: string
                  description: |
                    JSON stringified array of locations, e.g. '[{"city":"City","state":"State","coordinates":{"lan":77.1,"lat":28.6}}]'
      responses:
        '201':
          description: Service created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error
    get:
      summary: Get all services with optional filters
      tags:
        - Service
      parameters:
        - in: query
          name: categoryId
          schema:
            type: string
          description: The ObjectId of the category
        - in: query
          name: minPrice
          schema:
            type: number
          description: Minimum price
        - in: query
          name: maxPrice
          schema:
            type: number
          description: Maximum price
        - in: query
          name: avgRating
          schema:
            type: number
          description: Minimum average rating
        - in: query
          name: isFeatured
          schema:
            type: boolean
          description: Filter for featured services
        - in: query
          name: city
          schema:
            type: string
          description: Filter by city (locationAvailable)
        - in: query
          name: state
          schema:
            type: string
          description: Filter by state (locationAvailable)
        - in: query
          name: lan
          schema:
            type: number
          description: Filter by longitude (locationAvailable.coordinates.lan)
        - in: query
          name: lat
          schema:
            type: number
          description: Filter by latitude (locationAvailable.coordinates.lat)
      responses:
        '200':
          description: Services retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      Service:
                        type: object
                        properties:
                          _id:
                            type: string
                          title:
                            type: string
                            maxLength: 100
                          description:
                            type: string
                          category:
                            type: string
                          price:
                            type: number
                            minimum: 0
                          duration:
                            type: number
                            minimum: 0
                          media:
                            type: array
                            maxItems: 5
                            items:
                              type: string
                          avgRating:
                            type: number
                            minimum: 0
                            maximum: 5
                          ratingsCount:
                            type: number
                            minimum: 0
                          isActive:
                            type: boolean
                          isFeatured:
                            type: boolean
                          locationAvailable:
                            type: array
                            items:
                              type: object
                              properties:
                                city:
                                  type: string
                                state:
                                  type: string
                                coordinates:
                                  type: object
                                  properties:
                                    lan:
                                      type: number
                                    lat:
                                      type: number
                          createdAt:
                            type: string
                            format: date-time
                          updatedAt:
                            type: string
                            format: date-time
                  message:
                    type: string
                    example: Services retrieved successfully
        '400':
          description: Invalid filter
        '404':
          description: No services found
        '500':
          description: Server error
  /services/featured-services:
    get:
      summary: Get featured services
      tags:
        - Service
      responses:
        '200':
          description: Featured services retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      $ref: '#/paths/~1services/get/responses/200/content/application~1json/schema/properties/data/items'
                  message:
                    type: string
                    example: Featured services retrieved successfully
        '500':
          description: Server error
  /categories:
    get:
      summary: Get all categories
      tags:
        - Categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/paths/~1categories/post/responses/201/content/application~1json/schema/properties/data'
                  message:
                    type: string
    post:
      summary: Create a new category
      tags:
        - Categories
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                icon:
                  type: string
                  format: binary
      responses:
        '201':
          description: Category created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    required:
                      - name
                      - description
                      - icon
                    properties:
                      _id:
                        type: string
                        description: Category ID
                      name:
                        type: string
                      description:
                        type: string
                      icon:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time
                  message:
                    type: string
  /users/current-user:
    get:
      summary: Get current authenticated user's details
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
  /users/update-account:
    patch:
      summary: Update account details for the current user
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
                phoneNumber:
                  type: string
      responses:
        '200':
          description: Account details updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user: '$ref:''./../../schemas/User.yaml#/User'''
        '400':
          description: Bad request
  /users/avatar:
    patch:
      summary: Update the user's avatar
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          description: Avatar image updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Avatar file is missing
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        email:
          type: string
        googleId:
          type: string
        fullName:
          type: string
        avatar:
          type: string
        password:
          type: string
        isActive:
          type: boolean
        isVerified:
          type: boolean
        role:
          type: string
          enum:
            - user
            - provider
            - admin
        aadhar:
          type: object
          properties:
            link:
              type: string
            number:
              type: string
              maxLength: 12
            isVerified:
              type: boolean
        pan:
          type: object
          properties:
            link:
              type: string
            number:
              type: string
              maxLength: 10
            isVerified:
              type: boolean
        refreshToken:
          type: string
    Service:
      $ref: '#/paths/~1services/get/responses/200/content/application~1json/schema/properties/data/items/Service'
